name: Lint Plugins

on:
  pull_request:
    paths:
      - 'plugins/**'
      - '.claude-plugin/**'
      - '.github/workflows/lint-plugins.yml'
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Pull claudelint Docker image
        run: docker pull ghcr.io/stbenjam/claudelint:main
      
      - name: Run claudelint
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ghcr.io/stbenjam/claudelint:main \
            -v --strict
      
      - name: Comment on PR (on failure)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `⚠️ Plugin linter found issues.
            
            Run locally to see details:
            \`\`\`bash
            docker run --rm -v $(pwd):/workspace ghcr.io/stbenjam/claudelint:main
            \`\`\`
            
            Or install and run directly:
            \`\`\`bash
            pip install claudelint
            claudelint
            \`\`\`
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
